- hosts: namenode 
  vars_files:
          - var.yml
  tasks:
          - name: Copying JDK file to Target Node 
            copy:
                  dest: "/root/"
                  src: "/ansible-ws/task-11.1/jdk-8u171-linux-x64.rpm"

          - name: Copying Hadoop software to Target Node
            copy:
                  dest: "/root/"
                  src: "/ansible-ws/task-11.1/hadoop-1.2.1-1.x86_64.rpm"

          - name: Installing Java 
            command: "rpm -ivh jdk-8u171-linux-x64.rpm"
            register: x
            ignore_errors: yes

          - name: Installing Java show output
            debug:
                  var: x.stdout

          - name: Installing Hadoop
            command: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"
            register: y
            ignore_errors: yes

          - name: Installing Hadoop show output
            debug:
                  var: y.stdout
          
          - name: Removing directory if already present
            shell: "rm -rf {{ master_dir }}"
            ignore_errors: yes
            register: rm_dir

          - name: output of rm dir
            debug:
                  var: rm_dir.stdout

          - name: creating a directory
            file:
                  state: directory
                  path: "{{ master_dir }}"

          - name: copy hdfs file
            copy:
                  dest: "/etc/hadoop/hdfs-site.xml"
                  src: "/ansible-ws/task-11.1/hdfs-site.xml"

          - name: copy core file
            copy:
                  dest: "/etc/hadoop/core-site.xml"
                  src: "/ansible-ws/task-11.1/core-site.xml"

          - name: writing hdfs file
            blockinfile:
                  path: "/etc/hadoop/hdfs-site.xml"
                  insertafter: <property>
                  block: |
                         <name>{{ master }}</name>
                         <value>{{ master_dir }}</value>
          - debug:
                  var: groups['namenode']

          - name: writing core file
            blockinfile:
                  path: "/etc/hadoop/core-site.xml"
                  insertafter: </name>
                  block: 
                          <value>hdfs://{{ ansible_facts["default_ipv4"]["address"] }}:9001</value> 

          - name: stop namenode if already running
            shell: "hadoop-daemon.sh stop namenode"
            ignore_errors: yes
            register: "stop_namenode"

          - name: printing output of stopping namenode
            debug:
                  var: stop_namenode.stdout

          - name: formating the directory
            shell: "echo Y | hadoop namenode -format"

          - name: starting the namenode service
            command: "hadoop-daemon.sh start namenode"
            ignore_errors: yes
            register: start_namenode

          - name: output of namenode service
            debug:
                  var: start_namenode.stdout

          - name: checking the jps
            command: "jps"
            register: run_jps

          - name: output of jps
            debug:
                  var: run_jps.stdout

          - name: report of HDFS
            command: "hadoop dfsadmin -report"
            register: report

          - name: output of HDFS report
            debug:
                  var: report.stdout
